### ISSUE TITLE
The indent line is working abnormally

### ISSUE THREAD

**Issue by lexiaoyao12138** [yaocccc/nvim-hlchunk#2]
![GIF 21-2-2023 下午 7-32-14](https://user-images.githubusercontent.com/91322401/220334585-9aa38113-677f-41eb-ab63-78796e999084.gif)

## env:
 - windows terminal
 - nvim v0.8.3
 - format plug:  "mhartington/formatter.nvim"
 - format tool: clang-format
 - language: cpp
 ---
**After the code is formatted, the indent line advances one space to the right**

**Comment by yaocccc** [comment]
关注到了，请复制格式化前、格式化后的原始字符回复一下。

**Comment by yaocccc** [comment]
请测试，格式化后 zl，观察是否正常

**Comment by yaocccc** [comment]
或者 修改 plugin/hlchunk.vim第10行为

```
exec('au BufEnter,BufRead,TextChanged,TextChangedI,TextChangedP,CursorHold ' .. s:hlchunk_files .. ' let b:hlchunk_textoff=getwininfo(win_getid())[0].textoff')

```

**Comment by lexiaoyao12138** [comment]
## before 
`wininfo:`  *[{'winnr': 2, 'variables': {'nvimgdb_termwin_command': 'rightbelow vnew', 'nvimgdb_codewin_command': 'vnew'}, 'botline': 17, 'height': 42, 'bufnr': 9, 'winbar': 1, 'width': 135, 'tabnr': 1, 'quickfix': 0, 'topline': 1, 'loclist': 0, 'wincol': 32, 'winrow': 2, 'textoff': 5, 'winid': 1000, 'terminal': 0}*
```cpp
$
#include "Include/EchoServer.hpp"$
$
int main() {$
  EchoServer server(4, 10, "127.0.0.1", 8888);$
  server.start();$
^Iif (1) {$
^I^I//test...$
^I}$
^Ielse {$
^I^I//test$
^I}$
$
  // server.stop();$
  return 0;$
}$
```
## after
`wininfo:` *[{'winnr': 2, 'variables': {'paren_hl_on': 1, 'nvimgdb_termwin_command': 'rightbelow vnew', 'nvimgdb_codewin_command': 'vnew'}, 'botline': 18, 'height': 42, 'bufnr': 9, 'winbar': 1, 'width': 135, 'tabnr': 1, 'quickfix': 0, 'topline': 1, 'loclist': 0, 'wincol': 32, 'winrow': 2, 'textoff': 7, 'winid': 1000, 'terminal': 0}*
```cpp
$
#include "Include/EchoServer.hpp"$
$
int main() {$
  EchoServer server(4, 10, "127.0.0.1", 8888);$
  server.start();$
  if (1)$
  {$
    // test...$
  }$
  else$
  {$
    // test$
  }$
$
  // server.stop();$
  return 0;$
}$
```

**Comment by lexiaoyao12138** [comment]
怀疑是代码格式化以后，左侧边栏显示各种信息导致整体向右，关闭显示的插件后，插件工作正常

**Comment by yaocccc** [comment]
textoff 发生变化。奇怪的

**Comment by yaocccc** [comment]
在格式化前后打印一下

[b:hlchunk_textoff, getwininfo(win_getid())[0].textoff]

**Comment by lexiaoyao12138** [comment]
before [7,7]
after [5,7]

**Comment by yaocccc** [comment]
我知道哪里的问题了，因为我有地方有 缓存hlchunk_textoff的，但你格式的时候，这玩意变的顺序古怪，缓存了错误的，又不更新

**Comment by yaocccc** [comment]
你拉取试试看

**Comment by lexiaoyao12138** [comment]
**默认情况下已经正常， 但是如果左侧出现nerd fonts时，还是会错位**
![GIF 22-2-2023 下午 4-02-11](https://user-images.githubusercontent.com/91322401/220559283-97b224cc-acf4-403c-b28f-68f05030dddc.gif)
这种情况怎么解决

**Comment by yaocccc** [comment]
话说，其实可以设置signcolumn = yes的

**Comment by yaocccc** [comment]
看起来是signcolumn突然出现，导致它错位

**Comment by yaocccc** [comment]
算了，我把那个多余的缓存逻辑去掉了，现在肯定好了

**Comment by yaocccc** [comment]
另外我想问一下
 
 你的foldcolumn有什么修改么，和我的符号不同

![image](https://user-images.githubusercontent.com/53512609/220563713-dfb39782-dcd2-4593-b3f9-427a333cb58d.png)

顺便再推荐一下 set signcolumn=yes
搭配我的一个插件 vim-foldsign

**Comment by lexiaoyao12138** [comment]
flod 配置
![image](https://user-images.githubusercontent.com/91322401/220564783-b27d3949-e6a4-4358-a8fe-3a1701529ebd.png)
![image](https://user-images.githubusercontent.com/91322401/220564297-8363cdc3-f447-43df-ac29-15cc69e8e35a.png)
这个issue可以关掉了

**Comment by yaocccc** [comment]
ok，我去看看它怎么实现的

**Comment by yaocccc** [comment]
这个foldcolumn最烦的问题就是超过1级的时候，会显示成数字。看起来贼割裂。所以我写了个

nvim-foldsign
