### ISSUE TITLE
当使用 nowrap 时可以使用 winsaveview 函数获取当前窗口信息来简化操作

### ISSUE THREAD

**Issue by shellRaining** [yaocccc/nvim-hlchunk#3]
我注意到大佬你在处理 nowrap 时候使用了这个函数

```vimscript
func! s:get_scrolled()
    let virt_col = nvim_eval_statusline("%v", {}).str - 1
    let screen_col = screencol() - getwininfo(win_getid())[0].textoff - win_screenpos(0)[1]
    return virt_col - screen_col
endf
```

不过 vim 提供了获取当前窗口信息的一个函数 winsaveview，这个函数返回一个表，其中包含当前窗口的偏移量，可以简化操作，一个例子如下 [link](https://github.com/shellRaining/hlchunk.nvim/blob/main/lua/hlchunk/mods/indent.lua#L28)

**Comment by yaocccc** [comment]
非常感谢，这个信息困扰了我很久

**Comment by shellRaining** [comment]
> 非常感谢，这个信息困扰了我很久

这个我也是在indent blankline仓库里学到的，不得不说那个项目实现的效果真的很棒，就是代码实在是感觉晦涩难懂

**Comment by yaocccc** [comment]
是了是了，hhhh，复杂度一高，就很难看明白了，别说别人了，隔段时间，自己回来都看不懂了
